shoulder_pan_joint: -1.3
shoulder_lift_joint: -0.8
elbow_joint: -1.8
wrist_1_joint: -1.57
wrist_2_joint: 1.638
wrist_3_joint: 0.0

#move rt
# shoulder_pan_joint: -1.57
# shoulder_lift_joint: -0.7433
# elbow_joint: -1.7623
# wrist_1_joint: -2.3667
# wrist_2_joint: 1.569
# wrist_3_joint: 5.38

# shoulder_pan_joint: 0.0
# shoulder_lift_joint: -1.936
# elbow_joint: -1.378
# wrist_1_joint: -1.5
# wrist_2_joint: 0.0
# wrist_3_joint: -1.465


# shoulder_pan_joint: 0.0
# shoulder_lift_joint: -0.7433
# elbow_joint: -1.9623
# wrist_1_joint: 0.0
# wrist_2_joint: 0.0
# wrist_3_joint: 0.0

#vicino al cavo

# shoulder_pan_joint: -0.5887574182828947
# shoulder_lift_joint: -1.1629745959248332
# elbow_joint: -1.9154302468089848
# wrist_1_joint: -1.2348277713171043
# wrist_2_joint: 1.993864076236953
# wrist_3_joint: 0.5862039753002231
